CREATE TABLE MEMBER_TB(
	USERNAME VARCHAR2(20) PRIMARY KEY,
	PASSWORD VARCHAR2(100) NOT NULL,
	ENABLED NUMBER NOT NULL
)
INSERT INTO MEMBER_TB VALUES(
'member','1234',1
)

SELECT *
FROM MEMBER_TB JOIN AUTHORITIES USING(USERNAME) JOIN MEMBER_INFO USING(USERNAME)
WHERE USERNAME = 'member'

INSERT INTO MEMBER_TB VALUES(
'admin','1234',1
)
DROP TABLE MEMBER_INFO
CREATE SEQUENCE MEMBER_SQ;
CREATE TABLE MEMBER_INFO(
	NO NUMBER PRIMARY KEY,
	USERNAME VARCHAR2(20),
	NAME VARCHAR2(20),
	GENDER VARCHAR2(10)
)
INSERT INTO MEMBER_INFO VALUES(
MEMBER_SQ.NEXTVAL, 'member','멤버','M'
)
INSERT INTO MEMBER_INFO VALUES(
MEMBER_SQ.NEXTVAL, 'admin','어드민','F'
)



DROP TABLE AUTHORITIES
CREATE TABLE AUTHORITIES(
	USERNAME VARCHAR2(20) PRIMARY KEY,
	AUTHORITY VARCHAR2(20) NOT NULL
)
INSERT INTO AUTHORITIES VALUES(
'member','ROLE_MEMBER'
)
INSERT INTO AUTHORITIES VALUES(
'admin','ROLE_ADMIN'
)

ALTER TABLE AUTHORITIES
ADD CONSTRAINT FK_USERNAME FOREIGN KEY(USERNAME) REFERENCES MEMBER_TB(USERNAME)
